### ISSUE TITLE
RepoDB Conversion Script Fails

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#298]
While testing for https://github.com/RTXteam/RTX-KG2/issues/296, I found that repodb_csv_to_kg_json.py fails:

```
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,
Traceback (most recent call last):
  File "repodb_csv_to_kg_json.py", line 75, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "repodb_csv_to_kg_json.py", line 43, in make_kg2_graph
    knowledge_source=REPODB_CURIE + ':')]
TypeError: make_node() got an unexpected keyword argument 'knowledge_source'
```

Also note, our CSV of this source hasn't been updated since October 2019. We might want to examine whether this is still a valuable source since it is so outdated.

**Comment by ecwood** [comment]
I am closing this issue because the code worked in `KG2.8.4pre`'s build.
