### ISSUE TITLE
SemMedDB Conversion Fails

### ISSUE THREAD

**Issue by ecwood** [RTXteam/RTX-KG2#310]
While investigating for #296, I got this error for SemMedDB's conversion:

```
ubuntu@ip-172-31-59-112:~/kg2-build$ cat semmeddb_tuple_list_json_to_kg_json.log 
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,
Traceback (most recent call last):
  File "semmeddb_tuple_list_json_to_kg_json.py", line 187, in <module>
    remapped_cuis = get_remapped_cuis(mrcui_file_name)
  File "semmeddb_tuple_list_json_to_kg_json.py", line 44, in get_remapped_cuis
    map_type = row[2]
IndexError: list index out of range
```

**Comment by ecwood** [comment]
This was actually a user error, so I'm going to mark this for verification. I committed 3ddd2ac to make the program less susceptible to user errors (with the MRCUI file).

**Comment by ecwood** [comment]
There is a new error:
```
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,
Traceback (most recent call last):
  File "semmeddb_tuple_list_json_to_kg_json.py", line 233, in <module>
    knowledge_source=SEMMEDDB_CURIE_PREFIX + ':')
TypeError: make_node() got an unexpected keyword argument 'knowledge_source'
```

**Comment by ecwood** [comment]
With [b69254b](https://github.com/RTXteam/RTX-KG2/commit/b69254b69eaaa28415123eb5c4f1b65b9139c312), the  SemMedDB conversion script finished.

**Comment by ecwood** [comment]
I am closing this issue because the code worked in `KG2.8.4pre`'s build.
